spring:
  application:
    name: tithe-management-system
  datasource:
    url: jdbc:mysql://localhost:3306/tithe-management?autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowLoadLocalInfile=true&allowPublicKeyRetrieval=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: false

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

constants:
  max-image-size: 2000KB
  max-file-size: 128000KB

